### PR TITLE
Remove feature flags [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Search is now live and we almost have end-to-end publishing so we not longer need feature flags.

### Changes proposed in this pull request
- Remove `AllowLiveView` feature flag
- Remove ALL feature flags code

### Guidance to review
Check for "View on website" CTA in sidebar

### CODE REVIEW

**Comment by benilovj** [comment]
Is it wise to remove all feature flag code? I suspect we will still want to hide certain features in future...

**Comment by dankmitchell** [comment]
@benilovj with the removal of `AllowLiveView` we no longer have any feature flags so the right thing todo is remove the logic and _if_ we add feature flags in the future we can re-add the code.

**Comment by benilovj** [comment]
Fair enough.

**Comment by timabell** [comment]
Also we might write a better version next time :-D

**Comment by defong** [comment]
Is this dead?

**Pull request closed without merging**
