### PR TITLE
Display empty string for vacancies when course is discontinued

### PR DESCRIPTION
**Pull request by tvararu**
Discontinued courses shouldn't display vacancies.

### After

screenshot 2018-10-19 at 11 48 01

### CODE REVIEW

**Comment by tvararu** [comment]
[Vacancies for courses and training locations in Publish](https://trello.com/c/vJEMadNS/480-vacancies-for-courses-and-training-locations-in-publish)

**Comment by tvararu** [comment]
@benilovj added + updated logic slightly based on more feedback

**Comment by benilovj** [comment]
It saddens me that this logic lives in the UI, not in the API.

**Comment by tvararu** [comment]
@benilovj the API sends short strings/enum-like data structs to the frontend, the frontend translates those to readable output for the user. There's an extra case we discovered for vacancies where we need to display an empty string; this could have been done on the API but it would have meant changing HasVacancies from a bool to a string and more upheaval than all this stuff. Either way I'm not dogmatic about where logic like this should sit; in the end so long as developers can quickly identify where it's coming from and make changes to it, either approach is fine. :)

**Pull request merged**
