### PR TITLE
Use ApiClient nuget package

### PR DESCRIPTION
**Pull request by the-daniel-rothig**
### Context

We changed the way we build the ApiClient to make it more readily consumable, as a nuget package

### Changes proposed in this pull request

Use the nuget.org package for GovUk.Education.ManageCourses.ApiClient by default, but also, give developers a convenient option to use a local ApiClient project for better side-by-side development

While I was at it I also switched over to a better deployment mechanism that circumvents [a bug I found in Travis](https://github.com/travis-ci/travis-ci/issues/9914)

### Guidance to review

All the code generation in /src/ui is gone. :tada: I have migrated the wrapper ManageApi.cs to the ui project and namespace.

I have added guidance for local development to the readme, but for devs not wishing to do side-by-side development, everything just works (TM)

### CODE REVIEW

**Comment by defong** [comment]
Almost...

Was expecting an environment variable as an condition.
ie

Use_local_manage_course_src

and default path or let it be overrided either by another environment variable or by setting a value in the property

dotnet run /p:local_manage_course_src "folder path"

rather then a comment of todo

**Comment by the-daniel-rothig** [comment]
@defong sorry but I disagree... the path on my system is `..\..\..\manage-courses-api\src\ManageCourses.ApiClient\ManageCourses.ApiClient.csproj` - that's way too verbose for an ad-hoc env variable imo.

Moreover, all of our other env variables are app settings that have app config files and user-secrets. To have an "odd one out" that can't be set in those alternative ways seems much more confusing than my proposed approach

**Comment by defong** [comment]
The reason for having the src to be configurable is to allow to resolve the shortcoming of 
`Update the path to the .csproj file to match your local environment, and don't commit it :)`

ManageCourses for src
```<property>
<ManageCourses_src>set default here file location or extract it from enviroment</ManageCourses_src>
</property>

...

<ProjectReference Include={ManageCourses_src} />

...
```


"odd one out"

Can live here as its developer related only

https://github.com/DFE-Digital/manage-courses-ui/blob/910c7b48491c3c3bbf4ded392890fefa09aff937/src/ui/Properties/launchSettings.json#L22

**Comment by the-daniel-rothig** [comment]
@defong Ah cool thanks, now I get it, will do it like that

**Pull request merged**
