### PR TITLE
[1902] Added redirects

### PR DESCRIPTION
**Pull request by defong**
### Context
Redirects to rails

### Changes proposed in this pull request
Added redirects to rails
for the following endpoints, `request access`, `about` & `details`
### Guidance to review

`"/organisations/" + $"{providerCode}/request-access"`
`"/organisations/" + $"{providerCode}/2019/about"`
`"/organisations/" + $"{providerCode}/2019/details"`

### CODE REVIEW

**Comment by defong** [comment]
[[XS] Redirect provider editing to Rails](https://trello.com/c/wJaEW1dc/1902-xs-redirect-provider-editing-to-rails)

**Comment by tvararu** [comment]
This needs to be done after https://trello.com/c/Uz4E5tDH/1872-xs-switch-provider-editing-to-rails

**Comment by defong** [comment]
related to https://github.com/DFE-Digital/manage-courses-frontend/pull/526

**Comment by tvararu** [comment]
🏁

**Pull request merged**
