### PR TITLE
Add course fee validation

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
#153 

### Changes proposed in this pull request
- Add number range validation, between 0 - 100,000 only.
- Add regex for numbers only

### Guidance to review
screen shot 2018-09-04 at 22 56 07

### CODE REVIEW

**Comment by the-daniel-rothig** [comment]
Currently the course fees input renders the number with comma (e.g. 123.0) which is not actually a valid input in the proposed regex. It is also not valid in browser navigation (the type of the input is "number" which doesn't allow for decimal points, at least in Chrome)

This means that the view model will always render invalid values which the user would have to fix up!

So I added a commit that renders our decimal as a whole number in the text input, e.g. 123.0 -> 123.

**Comment by the-daniel-rothig** [comment]
Agreed it should be int32... but I think that's a slightly more involved refactor, which we should probably track as high-priority tech debt.

`max` and `min` are a good idea, I'll add those

**Comment by the-daniel-rothig** [comment]
@Sau fixed min/max and carded up the `int?` refactor: https://trello.com/c/Ow1FvEwV/257-change-course-fees-data-type-from-decimal-to-int :+1:

**Comment by defong** [comment]
@dankmitchell not sure what you mean?
how would the values expected get set?

**Comment by dankmitchell** [comment]
@defong i'm referring to the last commit.

**Comment by the-daniel-rothig** [comment]
@dankmitchell just tested and it turns out razor doesn't set max and min by itself

**Comment by defong** [comment]
image

fees number val

@fofr ok?

**Pull request merged**
